---
apiVersion: v1
kind: Namespace
metadata:
  name: loadtest
  labels:
    istio-injection: "enabled"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-v1
  labels:
    name: load-test
    app: load-test
    version: v1
  namespace: loadtest
spec:
  replicas: 2
  selector:
    matchLabels:
      name: load-test
      app: load-test
      version: v1
  template:
    metadata:
      labels:
        name: load-test
        app: load-test
        version: v1
    spec:
      containers:
      - name: load-test
        image: weaveworksdemos/load-test:0.1.1
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 400m
            memory: 400Mi
        command: ["/bin/sh"]
        args: ["-c", "while true; do locust --host http://front-end.sock-shop.svc.cluster.local -f /config/locustfile.py --clients 5 --hatch-rate 5 --num-request 100 --no-web; done"]
      nodeSelector:
        beta.kubernetes.io/os: linux
