---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    name: helloworld
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: helloworld
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: helloworld
        image: europe-west3-docker.pkg.dev/cnpe-blue/sockshop/helloworld:latest
        resources:
          limits:
            cpu: 300m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: linux
