apiVersion: v1
kind: Service
metadata:
  name: helloworld
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: helloworld
  namespace: sock-shop
spec:
  selector:
    name: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80