---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-master-v1
  labels:
    name: queue-master
    app: queue-master
    version: v1
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: queue-master
      app: queue-master
      version: v1
  template:
    metadata:
      labels:
        name: queue-master
        app: queue-master
        version: v1
    spec:
      containers:
      - name: queue-master
        image: europe-west3-docker.pkg.dev/cnpe-blue/sockshop/queue-master:latest
        env:
         - name: JAVA_OPTS
           value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 300Mi
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: linux
