---
apiVersion: v1
kind: Service
metadata:
  name: queue-master
  labels:
    name: queue-master
    app: queue-master
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: queue-master
    app: queue-master